name: corbado_auth_firebase
description: Flutter package to enable passkey based authentication with Firebase powered by Corbado.
homepage: https://docs.corbado.com/overview/welcome
repository: https://github.com/corbado/flutter-passkeys/tree/main/packages/corbado_auth_firebase
version: 2.0.5
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  cloud_functions: ^4.5.8
  corbado_auth:
    path: ../corbado_auth
  corbado_frontend_api_client: ^2.1.1
  flutter:
    sdk: flutter
  flutter_keychain: ^2.4.0
  http: ^1.1.2
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  passkeys:
    path: ../passkeys/passkeys
  rxdart: ^0.27.7
  ua_client_hints:
    git:
      url: git@github.com:nubank/flutter_ua_client_hints.git
      path: ./
      ref: ca522cb7d59f6dc455fee52ad5066f2ed9a45ca1
  universal_html: ^2.2.4

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0

false_secrets:
  - /example/android/app/google-services.json
  - /example/ios/Runner/GoogleService-Info.plist
  - /example/lib/firebase_options.dart
